export const config = {
  api: {
    baseUrl: process.env.API_URL ?? 'http://localhost:3232',
  },
  auth: {
    sessionCookie: 'ai-history.session',
    userCookie: 'ai-history.user',
    maxAgeSeconds: 60 * 60 * 24 * 7,
  },
  routes: {
    home: '/home',
    journey: '/journey',
    stories: '/stories',
    session: (sessionId: string) => `/sessions/${sessionId}`,
    login: '/',
    register: '/register',
    forgotPassword: '/forgot-password',
    linkAccount: '/link-account',
    privacy: '/privacy',
    terms: '/terms',
    profile: '/profile',
    subscription: '/subscription',
    verifyEmail: '/verify-email',
    loginApi: '/api/auth/login',
    logoutApi: '/api/auth/logout',
    registerApi: '/api/auth/register',
    verifyEmailApi: '/api/auth/verify-email',
    resendVerificationApi: '/api/auth/resend-verification',
    temporaryUserApi: '/api/auth/temporary',
    convertAccountApi: '/api/auth/convert',
    adStories: (slug: string) => `/ad-stories/${slug}`,
    meApi: '/api/me',
    mePasswordApi: '/api/me/password',
    meCreditsApi: '/api/me/available-credits',
    sessionStartApi: '/api/session/start',
    subscriptionApi: '/api/subscriptions',
    subscriptionPlanApi: '/api/subscriptions/plan',
    subscriptionCheckoutApi: '/api/subscriptions/checkout',
    subscriptionPortalApi: '/api/subscriptions/portal',
    leadApi: '/api/leads',
    leadDetailApi: (id: string) => `/api/leads/${id}`,
  },
} as const;
